export const formIoData = {
    "display": "form",
    "components": [
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [
                        {
                            "label": "Prefix",
                            "labelPosition": "top",
                            "widget": "choicesjs",
                            "placeholder": "",
                            "description": "",
                            "tooltip": "",
                            "customClass": "",
                            "tabindex": "",
                            "hidden": false,
                            "hideLabel": false,
                            "uniqueOptions": false,
                            "autofocus": false,
                            "disabled": false,
                            "tableView": true,
                            "modalEdit": false,
                            "multiple": false,
                            "dataSrc": "values",
                            "defaultValue": "",
                            "data": {
                                "values": [
                                    {
                                        "label": "Mr",
                                        "value": "mr"
                                    },
                                    {
                                        "label": "Mrs",
                                        "value": "mrs"
                                    },
                                    {
                                        "label": "Miss",
                                        "value": "miss"
                                    },
                                    {
                                        "label": "Ms",
                                        "value": "ms"
                                    },
                                    {
                                        "label": "Prof",
                                        "value": "prof"
                                    },
                                    {
                                        "label": "Dr",
                                        "value": "dr"
                                    },
                                    {
                                        "label": "Other",
                                        "value": "other"
                                    }
                                ],
                                "resource": "",
                                "url": "",
                                "json": "",
                                "custom": ""
                            },
                            "dataType": "",
                            "idPath": "id",
                            "valueProperty": "",
                            "template": "<span>{{ item.label }}</span>",
                            "refreshOn": "",
                            "refreshOnBlur": "",
                            "clearOnRefresh": false,
                            "searchEnabled": true,
                            "selectThreshold": 0.3,
                            "readOnlyValue": false,
                            "customOptions": {},
                            "useExactSearch": false,
                            "persistent": true,
                            "protected": false,
                            "dbIndex": false,
                            "encrypted": false,
                            "clearOnHide": true,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "allowCalculateOverride": false,
                            "validateOn": "change",
                            "validate": {
                                "required": true,
                                "onlyAvailableItems": false,
                                "customMessage": "",
                                "custom": "",
                                "customPrivate": false,
                                "json": "",
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false
                            },
                            "unique": false,
                            "errorLabel": "",
                            "errors": "",
                            "key": "prefix",
                            "tags": [],
                            "properties": {},
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": "",
                                "json": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "attributes": {},
                            "overlay": {
                                "style": "",
                                "page": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "type": "select",
                            "indexeddb": {
                                "filter": {}
                            },
                            "selectFields": "",
                            "searchField": "",
                            "searchDebounce": 0.3,
                            "minSearch": 0,
                            "filter": "",
                            "limit": 100,
                            "redrawOn": "",
                            "input": true,
                            "prefix": "",
                            "suffix": "",
                            "dataGridLabel": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "allowMultipleMasks": false,
                            "addons": [],
                            "authenticate": false,
                            "ignoreCache": false,
                            "lazyLoad": true,
                            "fuseOptions": {
                                "include": "score",
                                "threshold": 0.3
                            },
                            "id": "eg0ag15"
                        }
                    ],
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "size": "md",
                    "currentWidth": 3
                },
                {
                    "components": [
                        {
                            "label": "First Name",
                            "tableView": true,
                            "validate": {
                                "required": true,
                                "custom": "",
                                "customPrivate": false,
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false,
                                "minLength": "",
                                "maxLength": "",
                                "pattern": ""
                            },
                            "key": "firstName",
                            "type": "textfield",
                            "input": true,
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": {
                                "type": "input"
                            },
                            "attributes": {},
                            "validateOn": "change",
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "overlay": {
                                "style": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": [],
                            "mask": false,
                            "inputType": "text",
                            "inputFormat": "plain",
                            "inputMask": "",
                            "displayMask": "",
                            "spellcheck": true,
                            "truncateMultipleSpaces": false,
                            "id": "ea3soe"
                        }
                    ],
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "size": "md",
                    "currentWidth": 3
                },
                {
                    "components": [
                        {
                            "label": "Middle Name",
                            "tableView": true,
                            "validate": {
                                "required": true,
                                "custom": "",
                                "customPrivate": false,
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false,
                                "minLength": "",
                                "maxLength": "",
                                "pattern": ""
                            },
                            "key": "middleName",
                            "type": "textfield",
                            "input": true,
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": {
                                "type": "input"
                            },
                            "attributes": {},
                            "validateOn": "change",
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "overlay": {
                                "style": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": [],
                            "mask": false,
                            "inputType": "text",
                            "inputFormat": "plain",
                            "inputMask": "",
                            "displayMask": "",
                            "spellcheck": true,
                            "truncateMultipleSpaces": false,
                            "id": "e0inalq"
                        }
                    ],
                    "size": "md",
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "currentWidth": 3
                },
                {
                    "components": [
                        {
                            "label": "Last Name",
                            "tableView": true,
                            "validate": {
                                "required": true,
                                "custom": "",
                                "customPrivate": false,
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false,
                                "minLength": "",
                                "maxLength": "",
                                "pattern": ""
                            },
                            "key": "lastName",
                            "type": "textfield",
                            "input": true,
                            "placeholder": "",
                            "prefix": "",
                            "customClass": "",
                            "suffix": "",
                            "multiple": false,
                            "defaultValue": null,
                            "protected": false,
                            "unique": false,
                            "persistent": true,
                            "hidden": false,
                            "clearOnHide": true,
                            "refreshOn": "",
                            "redrawOn": "",
                            "modalEdit": false,
                            "dataGridLabel": false,
                            "labelPosition": "top",
                            "description": "",
                            "errorLabel": "",
                            "tooltip": "",
                            "hideLabel": false,
                            "tabindex": "",
                            "disabled": false,
                            "autofocus": false,
                            "dbIndex": false,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "widget": {
                                "type": "input"
                            },
                            "attributes": {},
                            "validateOn": "change",
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": ""
                            },
                            "overlay": {
                                "style": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "allowCalculateOverride": false,
                            "encrypted": false,
                            "showCharCount": false,
                            "showWordCount": false,
                            "properties": {},
                            "allowMultipleMasks": false,
                            "addons": [],
                            "mask": false,
                            "inputType": "text",
                            "inputFormat": "plain",
                            "inputMask": "",
                            "displayMask": "",
                            "spellcheck": true,
                            "truncateMultipleSpaces": false,
                            "id": "ea6f4lu"
                        }
                    ],
                    "size": "md",
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "currentWidth": 3
                }
            ],
            "autoAdjust": false,
            "customClass": "",
            "hidden": false,
            "hideLabel": false,
            "modalEdit": false,
            "key": "columns",
            "tags": [],
            "properties": {},
            "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
            },
            "customConditional": "",
            "logic": [],
            "attributes": {},
            "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
            },
            "type": "columns",
            "input": false,
            "tableView": false,
            "placeholder": "",
            "prefix": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "clearOnHide": false,
            "refreshOn": "",
            "redrawOn": "",
            "dataGridLabel": false,
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "calculateServer": false,
            "widget": null,
            "validateOn": "change",
            "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "allowMultipleMasks": false,
            "addons": [],
            "tree": false,
            "lazyLoad": false,
            "id": "eloth6p"
        },
        {
            "label": "Columns",
            "columns": [
                {
                    "components": [
                        {
                            "label": "Address",
                            "labelPosition": "top",
                            "placeholder": "",
                            "description": "",
                            "tooltip": "",
                            "prefix": "",
                            "suffix": "",
                            "widget": {
                                "type": "input"
                            },
                            "displayMask": "",
                            "editor": "",
                            "autoExpand": false,
                            "customClass": "",
                            "tabindex": "",
                            "autocomplete": "",
                            "hidden": false,
                            "hideLabel": false,
                            "showWordCount": false,
                            "showCharCount": false,
                            "autofocus": false,
                            "spellcheck": true,
                            "disabled": false,
                            "tableView": true,
                            "modalEdit": false,
                            "multiple": false,
                            "defaultValue": "",
                            "persistent": true,
                            "inputFormat": "html",
                            "protected": false,
                            "dbIndex": false,
                            "case": "",
                            "truncateMultipleSpaces": false,
                            "encrypted": false,
                            "redrawOn": "",
                            "clearOnHide": true,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "allowCalculateOverride": false,
                            "validateOn": "change",
                            "validate": {
                                "required": true,
                                "pattern": "",
                                "customMessage": "",
                                "custom": "",
                                "customPrivate": false,
                                "json": "",
                                "minLength": "",
                                "maxLength": "",
                                "minWords": "",
                                "maxWords": "",
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false
                            },
                            "unique": false,
                            "errorLabel": "",
                            "errors": "",
                            "key": "address",
                            "tags": [],
                            "properties": {},
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": "",
                                "json": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "attributes": {},
                            "overlay": {
                                "style": "",
                                "page": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "type": "textarea",
                            "rows": 3,
                            "wysiwyg": false,
                            "input": true,
                            "refreshOn": "",
                            "dataGridLabel": false,
                            "allowMultipleMasks": false,
                            "addons": [],
                            "mask": false,
                            "inputType": "text",
                            "inputMask": "",
                            "fixedSize": true,
                            "id": "eo2d12qh"
                        }
                    ],
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "size": "md",
                    "currentWidth": 3,
                    "width": 3
                },
                {
                    "components": [
                        {
                            "label": "Pin Code",
                            "labelPosition": "top",
                            "placeholder": "",
                            "description": "",
                            "tooltip": "",
                            "prefix": "",
                            "suffix": "",
                            "widget": {
                                "type": "input"
                            },
                            "inputMask": "",
                            "displayMask": "",
                            "allowMultipleMasks": false,
                            "customClass": "",
                            "tabindex": "",
                            "autocomplete": "",
                            "hidden": false,
                            "hideLabel": false,
                            "showWordCount": false,
                            "showCharCount": false,
                            "mask": false,
                            "autofocus": false,
                            "spellcheck": true,
                            "disabled": false,
                            "tableView": true,
                            "modalEdit": false,
                            "multiple": false,
                            "defaultValue": "",
                            "persistent": true,
                            "inputFormat": "plain",
                            "protected": false,
                            "dbIndex": false,
                            "case": "",
                            "truncateMultipleSpaces": false,
                            "encrypted": false,
                            "redrawOn": "",
                            "clearOnHide": true,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "allowCalculateOverride": false,
                            "validateOn": "change",
                            "validate": {
                                "required": true,
                                "pattern": "",
                                "customMessage": "",
                                "custom": "",
                                "customPrivate": false,
                                "json": "",
                                "minLength": "",
                                "maxLength": "",
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false
                            },
                            "unique": false,
                            "errorLabel": "",
                            "errors": "",
                            "key": "pinCode",
                            "tags": [],
                            "properties": {},
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": "",
                                "json": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "attributes": {},
                            "overlay": {
                                "style": "",
                                "page": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "type": "textfield",
                            "input": true,
                            "refreshOn": "",
                            "dataGridLabel": false,
                            "addons": [],
                            "inputType": "text",
                            "id": "e34ep8b"
                        }
                    ],
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "size": "md",
                    "currentWidth": 3,
                    "width": 3
                },
                {
                    "components": [
                        {
                            "label": "City",
                            "labelPosition": "top",
                            "placeholder": "",
                            "description": "",
                            "tooltip": "",
                            "prefix": "",
                            "suffix": "",
                            "widget": {
                                "type": "input"
                            },
                            "inputMask": "",
                            "displayMask": "",
                            "allowMultipleMasks": false,
                            "customClass": "",
                            "tabindex": "",
                            "autocomplete": "",
                            "hidden": false,
                            "hideLabel": false,
                            "showWordCount": false,
                            "showCharCount": false,
                            "mask": false,
                            "autofocus": false,
                            "spellcheck": true,
                            "disabled": false,
                            "tableView": true,
                            "modalEdit": false,
                            "multiple": false,
                            "defaultValue": "",
                            "persistent": true,
                            "inputFormat": "plain",
                            "protected": false,
                            "dbIndex": false,
                            "case": "",
                            "truncateMultipleSpaces": false,
                            "encrypted": false,
                            "redrawOn": "",
                            "clearOnHide": true,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "allowCalculateOverride": false,
                            "validateOn": "change",
                            "validate": {
                                "required": true,
                                "pattern": "",
                                "customMessage": "",
                                "custom": "",
                                "customPrivate": false,
                                "json": "",
                                "minLength": "",
                                "maxLength": "",
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false
                            },
                            "unique": false,
                            "errorLabel": "",
                            "errors": "",
                            "key": "city",
                            "tags": [],
                            "properties": {},
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": "",
                                "json": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "attributes": {},
                            "overlay": {
                                "style": "",
                                "page": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "type": "textfield",
                            "input": true,
                            "refreshOn": "",
                            "dataGridLabel": false,
                            "addons": [],
                            "inputType": "text",
                            "id": "e1g0zzf"
                        }
                    ],
                    "size": "md",
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "currentWidth": 3
                },
                {
                    "components": [
                        {
                            "label": "Upload Photo",
                            "labelPosition": "top",
                            "description": "",
                            "tooltip": "",
                            "customClass": "",
                            "tabindex": "",
                            "hidden": false,
                            "hideLabel": false,
                            "autofocus": false,
                            "disabled": false,
                            "tableView": false,
                            "modalEdit": false,
                            "storage": "url",
                            "dir": "",
                            "fileNameTemplate": "",
                            "image": true,
                            "uploadOnly": true,
                            "webcam": true,
                            "fileTypes": [
                                {
                                    "label": "",
                                    "value": ""
                                }
                            ],
                            "filePattern": "image/*",
                            "fileMinSize": "0KB",
                            "fileMaxSize": "2MB",
                            "multiple": false,
                            "persistent": true,
                            "protected": false,
                            "dbIndex": false,
                            "encrypted": false,
                            "redrawOn": "",
                            "clearOnHide": true,
                            "customDefaultValue": "",
                            "calculateValue": "",
                            "calculateServer": false,
                            "allowCalculateOverride": false,
                            "validate": {
                                "required": false,
                                "customMessage": "",
                                "custom": "",
                                "customPrivate": false,
                                "json": "",
                                "strictDateValidation": false,
                                "multiple": false,
                                "unique": false
                            },
                            "errorLabel": "",
                            "errors": "",
                            "key": "photo",
                            "tags": [],
                            "properties": {},
                            "conditional": {
                                "show": null,
                                "when": null,
                                "eq": "",
                                "json": ""
                            },
                            "customConditional": "",
                            "logic": [],
                            "attributes": {},
                            "overlay": {
                                "style": "",
                                "page": "",
                                "left": "",
                                "top": "",
                                "width": "",
                                "height": ""
                            },
                            "type": "file",
                            "options": {},
                            "privateDownload": false,
                            "imageSize": "200",
                            "input": true,
                            "placeholder": "",
                            "prefix": "",
                            "suffix": "",
                            "defaultValue": null,
                            "unique": false,
                            "refreshOn": "",
                            "dataGridLabel": false,
                            "widget": null,
                            "validateOn": "change",
                            "showCharCount": false,
                            "showWordCount": false,
                            "allowMultipleMasks": false,
                            "addons": [],
                            "id": "e6ezq5",
                            "url": "http://localhost:8081/api/web/upload/photo",
                            "fileKey": "",
                            "webcamSize": ""
                        }
                    ],
                    "size": "md",
                    "width": 3,
                    "offset": 0,
                    "push": 0,
                    "pull": 0,
                    "currentWidth": 3
                }
            ],
            "autoAdjust": false,
            "customClass": "",
            "hidden": false,
            "hideLabel": false,
            "modalEdit": false,
            "key": "columns1",
            "tags": [],
            "properties": {},
            "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
            },
            "customConditional": "",
            "logic": [],
            "attributes": {},
            "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
            },
            "type": "columns",
            "input": false,
            "tableView": false,
            "placeholder": "",
            "prefix": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "clearOnHide": false,
            "refreshOn": "",
            "redrawOn": "",
            "dataGridLabel": false,
            "labelPosition": "top",
            "description": "",
            "errorLabel": "",
            "tooltip": "",
            "tabindex": "",
            "disabled": false,
            "autofocus": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "calculateServer": false,
            "widget": null,
            "validateOn": "change",
            "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "allowMultipleMasks": false,
            "addons": [],
            "tree": false,
            "lazyLoad": false,
            "id": "ejvssb"
        },
        {
            "label": "Submit",
            "action": "submit",
            "showValidations": false,
            "theme": "primary",
            "size": "md",
            "block": false,
            "leftIcon": "fa fa-check",
            "rightIcon": "",
            "shortcut": "",
            "description": "",
            "tooltip": "",
            "customClass": "pull-right mt-4",
            "tabindex": "",
            "disableOnInvalid": true,
            "hidden": false,
            "autofocus": false,
            "disabled": false,
            "tableView": false,
            "modalEdit": false,
            "key": "submit",
            "tags": [],
            "properties": {},
            "conditional": {
                "show": null,
                "when": null,
                "eq": "",
                "json": ""
            },
            "customConditional": "",
            "logic": [],
            "attributes": {},
            "overlay": {
                "style": "",
                "page": "",
                "left": "",
                "top": "",
                "width": "",
                "height": ""
            },
            "type": "button",
            "input": true,
            "placeholder": "",
            "prefix": "",
            "suffix": "",
            "multiple": false,
            "defaultValue": null,
            "protected": false,
            "unique": false,
            "persistent": false,
            "clearOnHide": true,
            "refreshOn": "",
            "redrawOn": "",
            "dataGridLabel": true,
            "labelPosition": "top",
            "errorLabel": "",
            "hideLabel": false,
            "dbIndex": false,
            "customDefaultValue": "",
            "calculateValue": "",
            "calculateServer": false,
            "widget": {
                "type": "input"
            },
            "validateOn": "change",
            "validate": {
                "required": false,
                "custom": "",
                "customPrivate": false,
                "strictDateValidation": false,
                "multiple": false,
                "unique": false
            },
            "allowCalculateOverride": false,
            "encrypted": false,
            "showCharCount": false,
            "showWordCount": false,
            "allowMultipleMasks": false,
            "addons": [],
            "id": "ebxvdyv",
            "saveOnEnter": false
        }
    ]
}